%TEST_HIGH_FIDELITY WGS84 geometry, Earth rates and mechanization regressions.

% Geodetic/ECEF/reference-NED transforms must be mutually consistent.
llaCases = [0, 50.478, -33.9, 80; 0, 12.365, 151.2, -45; 0, 430, 1200, 50];
for i = 1:size(llaCases,2)
    lla = llaCases(:,i);
    llaBack = ecef2lla(lla2ecef(lla));
    assert(max(abs(llaBack-lla)) < 2e-7, 'WGS84 LLA/ECEF round-trip failed');
end
ref = [50.478;12.365;430]; p = [25000;-12000;850];
assert(norm(lla2ned(ned2lla(p,ref),ref)-p) < 1e-6, ...
    'exact ECEF-chord NED round-trip failed');

% At a stationary equatorial site, Earth rate is entirely north-directed.
c = defaultConfig(); c.INS.earthModel='wgs84';
[wie,wen,win] = earthRatesNED([0;0;0],zeros(3,1),c);
assert(norm(wie-[7.292115e-5;0;0]) < 1e-14 && norm(wen)==0 && norm(win-wie)==0, ...
    'equatorial Earth-rate components are incorrect');
[wieM,wenM,winM]=earthRatesNED([45;10;500],[100;50;-2],c);
assert(norm(wieM)>0 && norm(wenM)>0 && norm(winM-wieM-wenM)<1e-18, ...
    'moving-site Earth/transport rates are incomplete');

% Earth-aware ESKF transition must contain transport/Coriolis coupling, and
% its higher-order process covariance must remain positive semidefinite.
k1=LooselyCoupledEKF(); k1.initState(c); k1.P(:)=0;
Phi1=k1.predict(eye(3),[0;0;-9.8],0.05,c,[45;10;500],[100;50;-2]);
cNo=c; cNo.INS.useCoriolis=false;
k0=LooselyCoupledEKF(); k0.initState(cNo); k0.P(:)=0;
Phi0=k0.predict(eye(3),[0;0;-9.8],0.05,cNo,[45;10;500],[100;50;-2]);
assert(norm(Phi1(4:6,4:6)-Phi0(4:6,4:6),'fro')>1e-8, ...
    'Coriolis/transport coupling is absent from ESKF dynamics');
assert(norm(Phi1(7:9,7:9)-eye(3),'fro')>1e-8, ...
    'Earth/transport rate is absent from attitude-error dynamics');
assert(min(eig(k1.P))>-1e-14, 'high-fidelity discrete process covariance is not PSD');

% Perfect IMU generated by earthTruth must remain matched by the WGS84 INS.
c.Sim.dt=0.02; c.Sim.duration=8; c.Traj.type='Straight'; c.Traj.speed=0;
c.Align.enabled=false; c.Fusion.mode='ins'; c.GNSS.enabled=false;
c.INS.useEarthRate=true; c.INS.useTransportRate=true; c.INS.useCoriolis=true;
c.INS.useConingSculling=false;
for f = {'useGyroBias','useGyroNoise','useGyroSF','useGyroMis', ...
          'useAccelBias','useAccelNoise','useAccelSF','useAccelMis'}
    c.IMU.(f{1})=false;
end
e=SimEngine(c); e.runToEnd(); r=e.results();
assert(max(r.errPosIns) < 2e-4 && max(r.errVelIns) < 5e-5 && ...
       rad2deg(max(r.errAttIns)) < 2e-5, ...
    sprintf('stationary WGS84 perfect match failed: p %.3g m, v %.3g m/s, a %.3g deg', ...
    max(r.errPosIns),max(r.errVelIns),rad2deg(max(r.errAttIns))));

% Nonzero velocity activates transport and Coriolis in both Truth and INS.
cm=c; cm.Sim.duration=10; cm.Traj.speed=180;
em=SimEngine(cm); em.runToEnd(); rm=em.results();
assert(max(rm.errPosIns)<0.15 && max(rm.errVelIns)<0.03 && ...
       rad2deg(max(rm.errAttIns))<0.01, ...
    sprintf('moving WGS84 perfect match failed: p %.3g m, v %.3g m/s, a %.3g deg', ...
    max(rm.errPosIns),max(rm.errVelIns),rad2deg(max(rm.errAttIns))));

% Streaming coning uses the cross-coupling between consecutive increments.
cc=c; cc.INS.earthModel='flat'; cc.INS.gravity=9.80665;
m0=INSMechanization(); m1=INSMechanization();
cc.INS.useConingSculling=false; m0.reset(zeros(3,1),zeros(3,1),zeros(3,1),cc);
cc.INS.useConingSculling=true;  m1.reset(zeros(3,1),zeros(3,1),zeros(3,1),cc);
wA=[0.2;0;0]; wB=[0;0.3;0]; dt=0.1; f=zeros(3,1);
cc.INS.useConingSculling=false; m0.step(wA,f,dt,cc); m0.step(wB,f,dt,cc);
cc.INS.useConingSculling=true;  m1.step(wA,f,dt,cc); m1.step(wB,f,dt,cc);
assert(norm(m0.q-m1.q) > 1e-6, 'coning compensation did not affect crossed increments');
assert(norm(m1.C'*m1.C-eye(3),'fro') < 1e-12, 'coning update broke attitude orthogonality');

fprintf('  high fidelity: WGS84 rates/ESKF, static+moving Earth match and coning OK\n');
