classdef EduContent
%EDUCONTENT Short practical explanations for each pipeline stage (Persian).
methods (Static)
    function s = get(stage)
        s = struct('title', stage, 'body', 'No description available.');
        switch stage
            case 'Trajectory'
                s.title = 'Trajectory / Vehicle Motion';
                s.body = sprintf(['مسیر مرجع حرکت وسیله را به‌صورت تحلیلی تولید می‌کند.\n\n' ...
                    'خروجی: موقعیت، سرعت و شتاب در فریم NED محلی.\n' ...
                    'وضعیت (Roll/Pitch/Yaw) به‌صورت فیزیکی از جهت سرعت ساخته می‌شود:\n' ...
                    '  yaw = atan2(vE, vN)\n' ...
                    '  pitch = زاویه مسیر پرواز\n' ...
                    '  roll = چرخش هماهنگ: atan(V*d(psi)/dt / g)\n\n' ...
                    'پارامترهای مؤثر: نوع مسیر، سرعت، شعاع، نرخ صعود/دوران.']);
            case 'Truth'
                s.title = 'Truth State';
                s.body = sprintf(['حالت واقعی و بدون خطای سیستم است؛ مرجعِ مقایسه برای همه‌چیز.\n\n' ...
                    'خروجی در هر گام:\n' ...
                    '  p_n, v_n, a_n (NED)\n' ...
                    '  Euler angles + Euler rates\n' ...
                    '  نرخ زاویه‌ای واقعی بدنه: w = T(eul)*eulDot\n' ...
                    '  نیروی ویژه واقعی: f_b = C_n2b * (a_n - g_n)\n\n' ...
                    'این دو مقدار ورودیِ شبیه‌ساز IMU هستند.']);
            case 'IMU'
                s.title = 'IMU Simulation (Gyro + Accel)';
                s.body = sprintf(['از Truth، خروجی سنسور مصنوعی ساخته می‌شود:\n\n' ...
                    '  meas = (I + skew(misalign)) * diag(1+SF) * true + bias + noise\n\n' ...
                    'ورودی: نرخ زاویه‌ای و نیروی ویژه واقعی (body frame)\n' ...
                    'خروجی: gyro_meas [rad/s], accel_meas [m/s^2]\n\n' ...
                    'خطاهای مؤثر: Bias، Noise (ARW/VRW)، Scale Factor،\n' ...
                    'Misalignment، Random Walk بایاس.\n' ...
                    'نویز گسسته: sigma = density / sqrt(dt).']);
            case 'Calibration'
                s.title = 'IMU Processing / Calibration';
                s.body = sprintf(['تصحیح آنلاین خروجی IMU با بایاس‌های تخمینی فیلتر:\n\n' ...
                    '  w_c = w_meas - bg_est\n' ...
                    '  f_c = f_meas - ba_est\n\n' ...
                    'در حالت INS Only تخمینی وجود ندارد و خطاها مستقیم وارد INS می‌شوند.\n' ...
                    'در حالت GNSS+INS فیلتر بایاس‌ها را تخمین زده و اینجا اعمال می‌شود.']);
            case 'INS'
                s.title = 'INS Mechanization (Strapdown, NED)';
                s.body = sprintf(['انتگرال‌گیری از IMU در فریم NED محلی:\n\n' ...
                    '  Attitude:  q <- q (*) deltaQuat(w*dt)\n' ...
                    '  Transform: f_n = C_b2n * f_b\n' ...
                    '  Velocity:  v <- v + (f_n + g_n)*dt\n' ...
                    '  Position:  p <- p + v*dt (ذوزنقه‌ای)\n\n' ...
                    'ورودی: IMU کالیبره‌شده + dt\nخروجی: p, v, attitude\n' ...
                    'خطای مؤثر: هر خطای IMU مستقیم Drift ایجاد می‌کند؛\n' ...
                    'dt متغیر (Timing Error) نیز پشتیبانی می‌شود.\n' ...
                    '(ساده‌سازی آموزشی: چرخش زمین/Coriolis نادیده گرفته شده.)']);
            case 'Prediction'
                s.title = 'Prediction (Filter time update)';
                s.body = sprintf(['پخش کوواریانس خطا با مدل خطای ۱۵‌حالته:\n' ...
                    '  dx = [dp; dv; dphi; dbg; dba]\n\n' ...
                    '  dv_dot   = skew(f_n)*dphi - C*dba\n' ...
                    '  dphi_dot = +C*dbg   (error = true - estimate)\n' ...
                    '  bias‌ها: Random Walk\n\n' ...
                    '  P <- F*P*F^T + Qd\n\n' ...
                    'اگر GNSS نباشد، عدم‌قطعیت (سیگماها) رشد می‌کند —\n' ...
                    'این رشد را در Data Flow Monitor ببینید.']);
            case 'GNSS'
                s.title = 'GNSS Simulation';
                s.body = sprintf(['سنجش موقعیت (و اختیاری سرعت) با نرخ مشخص:\n\n' ...
                    '  z = p_true + bias + noise( sigma_H, sigma_V )\n\n' ...
                    'پدیده‌ها: Dropout (قطعی برنامه‌ریزی‌شده/تصادفی)،\n' ...
                    'Outlier (پرت ‌های بزرگ گاه‌به‌گاه)، Delay (تأخیر سنجش).\n\n' ...
                    'خروجی: z_p (+ z_v) به همراه ماتریس R برای فیلتر.']);
            case 'Fusion'
                s.title = 'Fusion / Measurement Update (Loosely Coupled EKF)';
                s.body = sprintf(['به‌روزرسانی خطا با سنجش GNSS (Error-State EKF):\n\n' ...
                    '  resid = z_gnss - p_ins\n' ...
                    '  S = H*P*H^T + R,  K = P*H^T/S\n' ...
                    '  dx <- dx + K*resid\n\n' ...
                    'سپس تصحیح فیدبکی: حالت INS و بایاس‌ها اصلاح و dx صفر می‌شود.\n' ...
                    'نتیجه: خطای موقعیت/سرعت/وضعیت کران‌دار می‌ماند و\n' ...
                    'بایاس‌های IMU به‌تدریج شناسایی می‌شوند.']);
            case 'Output'
                s.title = 'Navigation Estimate / Error Analysis';
                s.body = sprintf(['خروجی نهایی: تخمین p, v, attitude .\n\n' ...
                    'تحلیل خطا با مقایسه با Truth:\n' ...
                    '  err_pos  = ||p_est - p_true||\n' ...
                    '  err_vel  = ||v_est - v_true||\n' ...
                    '  err_att  = ||wrap(eul_est - eul_true)||\n\n' ...
                    'مقایسه‌ی INS در برابر Fused، ارزش Fusion را نشان می‌دهد.']);
            case 'Alignment'
                s.title = 'Initial Alignment';
                s.body = sprintf(['تخمین وضعیت اولیه پیش از شروع ناوبری — دو حالت:\n\n' ...
                    'الف) سکون (|v0| <= 1 m/s و |a0| <= 0.1 m/s2): Levelling با شتاب‌سنج:\n' ...
                    '  roll  = atan2(-fy, -fz)\n' ...
                    '  pitch = atan2(fx, sqrt(fy^2+fz^2))\n' ...
                    '  Heading با قطب‌نما (مدل ساده). میانگین‌گیری، نویز را با\n' ...
                    '  1/sqrt(n) کم می‌کند؛ همگرایی را در نمودار Attitude ببینید.\n\n' ...
                    'ب) حرکت (Transfer Alignment): حدس درشت از منبع خارجی\n' ...
                    '  (true + خطای coarse)؛ اصلاح نهایی با Fusion هنگام مانور.\n\n' ...
                    'خطای اولیه کاربر (Errors tab) در هر دو حالت قابل تزریق است.']);
            case 'Transform'
                s.title = 'Coordinate Transforms';
                s.body = sprintf(['تبدیلات فریم در این شبیه‌ساز:\n\n' ...
                    '  Body <-> NED:   C_b2n (Quaternion / DCM / Euler ZYX)\n' ...
                    '  NED <-> LLA:    شعاع‌های انحنای WGS84 (M, N)\n\n' ...
                    '  نرخ‌ها: w_body = T(eul) * eulDot\n\n' ...
                    'مرجع LLA پیش‌فرض: Lat 50.478, Lon 12.365, h=430m\n' ...
                    '(رابط کاربری: پنل INS & Align).']);
            otherwise
                s.body = 'Unknown stage.';
        end
    end

    function stages = list()
        stages = {'Trajectory','Truth','IMU','Calibration','INS','Prediction', ...
                  'GNSS','Fusion','Output'};
    end
end
end
